name: build-macos

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: macos-latest
    steps:
    - uses: actions/checkout@v3
      with:
        submodules: 'recursive'
        
    - name: Install Dependencies
      run: brew install ninja cmake

    - name: Configure CMake
      run: cmake -G Ninja -B ${{github.workspace}}/build -DVCPKG_BUILD_TYPE=release -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=$VCPKG_INSTALLATION_ROOT/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j

    - name: Install
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t install
        rm -f ${{github.workspace}}/install/README.md
        # Maintaining file permissions
        chmod +x ${{github.workspace}}/install/shadertoy
        mv ${{github.workspace}}/install ${{github.workspace}}/shadertoy-macos-universal
        tar -zcvf ${{github.workspace}}/shadertoy-macos-universal.tar.gz --directory ${{github.workspace}} shadertoy-macos-universal

    - uses: actions/upload-artifact@v3
      with:
        name: build-macos
        path: ${{github.workspace}}/shadertoy-macos-universal.tar.gz
        if-no-files-found: error
      