name: build-windows

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

env:
  BUILD_TYPE: Release

jobs:
  build:
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'

    - name: Configure CMake
      run: cmake -G "Visual Studio 17 2022" -A x64 -B ${{github.workspace}}/build -DX_VCPKG_APPLOCAL_DEPS_INSTALL=ON -DCMAKE_INSTALL_PREFIX=${{github.workspace}}/install -DCMAKE_BUILD_TYPE=${{env.BUILD_TYPE}} -DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake

    - name: Build
      run: cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -j
    
    - name: Install
      run: |
        cmake --build ${{github.workspace}}/build --config ${{env.BUILD_TYPE}} -t install
        rm -Force ${{github.workspace}}/install/README.md
        rm -Force ${{github.workspace}}/install/*.ilk
        rm -Force ${{github.workspace}}/install/*.pdb
    
    - uses: actions/upload-artifact@v4
      with:
        name: build-windows
        path: ${{github.workspace}}/install
        if-no-files-found: error
      
